### ISSUE TITLE
drw command issue

### ISSUE THREAD

**Issue by goessner** [goessner/g2-new#11]
With `g2.drw` pathes are drawn. With shadow style of closed pathes one usually doesn't want to have stroke-shadowsl *and* fill-shadows. So `g2.drw` suppresses stroke-shadows with fillstyle existent and not equal `transparent` by default.

In some rare cases (arrow with filled arrow head) one should be able to change that default behavior. This can be achieve by an additional property `lsh`, as in ...
```js
   g2().p() ...  drw({ls:'green',fs:'@ls',lsh:true})
```

So for activating this feature, please modify in g2.js and document accordingly

```js
    drw({d,lsh}={}) {
        let ctx = this.ctx,
            tmp = this.setStyle(arguments[0]),
            p = d && new Path2D(d);   // SVG path syntax 
        d ? ctx.fill(p) : ctx.fill();
        if (ctx.shadowColor !== 'rgba(0, 0, 0, 0)' && ctx.fillStyle !== 'rgba(0, 0, 0, 0)' && !lsh) {
           let shc = ctx.shadowColor;        // usually avoid stroke shadow when filling ...
           ctx.shadowColor = 'rgba(0, 0, 0, 0)';
           d ? ctx.stroke(p) : ctx.stroke();
           ctx.shadowColor = shc;
        }
        else
           d ? ctx.stroke(p) : ctx.stroke();
        this.resetStyle(tmp);
    },

```

**Comment by klawr** [comment]
Fixed in 943341b51c8d9410708d3cc9cf618de144bb1430
