### ISSUE TITLE
arrow head size in g2.vec

### ISSUE THREAD

**Issue by goessner** [goessner/g2-new#15]
seems to be a bit large (the black one as velocity) ...

![grafik](https://user-images.githubusercontent.com/4902746/43854234-95413554-9b42-11e8-9609-bec70dab3d1b.png)

Also with zero length vectors no lonely arrow head should be visible.

**Comment by klawr** [comment]
The `z`-value defines the breadth of the arrow and depends on `lw` through `const z = args.lw+2`
If i am not mistaken, this is the desired behaviour.
I made the `z`-value a editable property in 36deda223011dc7ab6bebbac126c8dd006db5c2f.
The size of the arrow can be adjusted now via `lw` and optionally `z`.

**Comment by goessner** [comment]
.. ok .. just give it a more memorizable name ..
