### ISSUE TITLE
parameterless beg command

### ISSUE THREAD

**Issue by goessner** [goessner/g2-new#8]
A parameterless `beg` command makes few sense, but it should be silently accepted without error message.

So we need to change 

```js
    beg({x,y,w,scl,matrix,unsizable}) {
```
into

```js
    beg({x,y,w,scl,matrix,unsizable}={}) {
```

**Comment by klawr** [comment]
Done in 4dc91de8f4f8d10866a2e1bfac7feb55479ada8e
